version: '3.8'
services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    image: popathemangi/recipe-server:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/recipebook
      - PORT=6001
    ports:
      - "6001:6001"
    depends_on:
      - mongo
    networks:
      - recipe-net

  client:
    image: popathemangi/recipe-client:latest
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - recipe-net

volumes:
  mongo-data:

networks:
  recipe-net:
    driver: bridge